In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/laptop_details.csv')
df.head()

Product  Rating      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...     4.2  ₹36,990   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...     4.2  ₹39,990   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...     4.3  ₹32,990   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...     4.4  ₹49,990   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...     4.4  ₹49,990   

                                             Feature  
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...  
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...  
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Product  720 non-null    object 
 1   Rating   581 non-null    float64
 2   MRP      720 non-null    object 
 3   Feature  720 non-null    object 
dtypes: float64(1), object(3)
memory usage: 22.6+ KB


In [ ]:
#Checking for Null Values

df.isnull().sum()

#There are 139 null values with ratings. Since it is a Float datatype we could use Mean or Median to fill the null values. Since the ratings are not a deciding factor for pricing it is dropped.

Product      0
Rating     139
MRP          0
Feature      0
dtype: int64

In [ ]:
#Dropping "Rating" feature 

df.drop ('Rating', axis = 1, inplace = True)
df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  ₹36,990   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  ₹39,990   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  ₹32,990   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  ₹49,990   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  ₹49,990   

                                             Feature  
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...  
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...  
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...

In [ ]:
#Checking for Duplicate Values

df.duplicated().sum()

299

In [ ]:
#Dropping Duplicates 
df = df.drop_duplicates()
df.duplicated().sum()

0

**FEATURE ENGINEERING AND FEATURE SELECTION**

In [ ]:
# Converting MRP to Float
df.MRP = df.MRP.str.replace('₹','').str.replace(',','')
df.MRP = df.MRP.astype(float)

In [ ]:
df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  36990.0   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  39990.0   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  32990.0   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  49990.0   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  49990.0   

                                             Feature  
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...  
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...  
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421 entries, 0 to 719
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Product  421 non-null    object 
 1   MRP      421 non-null    float64
 2   Feature  421 non-null    object 
dtypes: float64(1), object(2)
memory usage: 13.2+ KB


**FEATURE EXTRACTION**

In [ ]:
import re

In [ ]:
# New column Brand
# str.split() by space

df['Brand'] = df['Product'].apply(lambda x: x.split(" ")[0])

In [ ]:
df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  36990.0   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  39990.0   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  32990.0   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  49990.0   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  49990.0   

                                             Feature   Brand  
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo  
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo  
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...    ASUS  
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...      HP  
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...    ASUS

In [ ]:
df.Brand.unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [ ]:
#RAM_SIZE

df['RAM_Size'] = df['Feature'].apply(lambda x: int(re.findall(r'\d+', x.split('DDR')[0])[-1]))

In [ ]:
#RAM_TYPE

regex_ram_type = r'(DDR[0-9L]*|LPDDR[0-9X]*)'

def extract_ram_type(text):
    match = re.search(regex_ram_type, text, re.IGNORECASE)
    if match:
        return match.group(0)
    else:
        return None

df['RAM_Type'] = df['Feature'].apply(extract_ram_type)

In [ ]:
#STORAGE

df['Storage'] = df['Feature'].apply(lambda x: int(re.findall(r'\d+', x.split('SSD')[0])[-1]))

In [ ]:
#DISK TYPE

df['Disk_Type'] = df['Product'].apply(lambda x:'HDD' if 'HDD' in x else 'SSD' )

In [ ]:
df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  36990.0   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  39990.0   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  32990.0   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  49990.0   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  49990.0   

                                             Feature   Brand  RAM_Size  \
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...      HP         8   
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   

  RAM_Type  Storage Disk_Type  
0     DDR4      256       SSD  
1     DDR4      512       SSD  
2     DDR4      512       SSD  
3     DDR4      512       SSD  
4     DDR4      512       SSD

In [ ]:
df['OS_Type'] = df['Feature'].apply(lambda x: 'Windows' if 'Windows' in x else'Mac OS' if 'Mac OS' in x else 'Others')

df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  36990.0   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  39990.0   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  32990.0   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  49990.0   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  49990.0   

                                             Feature   Brand  RAM_Size  \
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...      HP         8   
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   

  RAM_Type  Storage Disk_Type  OS_Type  
0     DDR4      256       SSD  Windows  
1     DDR4      512       SSD  Windows  
2     DDR4      512       SSD  Windows  
3     DDR4      512       SSD  Windows  
4     DDR4      512       SSD  Windows

In [ ]:
regex_processor = r'(?:Intel|AMD)\s+[A-Za-z\d]+'

def extract_processor(text):
    match = re.search(regex_processor, text, re.IGNORECASE)
    if match:
        return match.group()
    else:
        return None

df['Processor'] = df['Feature'].apply(extract_processor)

In [ ]:
def extract_processor_brand(text):
    if re.search(r"intel", text, re.IGNORECASE):
        return "Intel"
    elif re.search(r"amd", text, re.IGNORECASE):
        return "AMD"
    else:
        return "Others"


df['Processor'] = df['Feature'].apply(extract_processor_brand)
df['Processor'].value_counts()

Intel     272
AMD       129
Others     20
Name: Processor, dtype: int64

In [ ]:
df.Processor.unique()

array(['Intel', 'AMD', 'Others'], dtype=object)

In [ ]:
df.head()

Product      MRP  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...  36990.0   
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...  39990.0   
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...  32990.0   
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...  49990.0   
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...  49990.0   

                                             Feature   Brand  RAM_Size  \
0  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
1  Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
2  Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   
3  AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...      HP         8   
4  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   

  RAM_Type  Storage Disk_Type  OS_Type Processor  
0     DDR4      256       SSD  Windows     Intel  
1     DDR4      512       SSD  Windows     Intel  
2     DDR4      512       SSD  Windows     Intel  
3     DDR4      512       SSD  Windows       AMD  
4     DDR4      512       SSD  Windows     Intel

In [ ]:
#All the necessary features needed for the Analysis have been extracted. Lets Proceed with the EDA.

**EDA**

In [ ]:
#RE-Arranging the Columns

data = df[['Brand', 'Processor', 'RAM_Type', 'RAM_Size', 'Storage','Disk_Type', 'OS_Type', 'MRP']]
data.head()

Brand Processor RAM_Type  RAM_Size  Storage Disk_Type  OS_Type      MRP
0  Lenovo     Intel     DDR4         8      256       SSD  Windows  36990.0
1  Lenovo     Intel     DDR4         8      512       SSD  Windows  39990.0
2    ASUS     Intel     DDR4         8      512       SSD  Windows  32990.0
3      HP       AMD     DDR4         8      512       SSD  Windows  49990.0
4    ASUS     Intel     DDR4         8      512       SSD  Windows  49990.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421 entries, 0 to 719
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Brand      421 non-null    object 
 1   Processor  421 non-null    object 
 2   RAM_Type   409 non-null    object 
 3   RAM_Size   421 non-null    int64  
 4   Storage    421 non-null    int64  
 5   Disk_Type  421 non-null    object 
 6   OS_Type    421 non-null    object 
 7   MRP        421 non-null    float64
dtypes: float64(1), int64(2), object(5)
memory usage: 29.6+ KB


**MODEL BUILDING**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421 entries, 0 to 719
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Brand      421 non-null    object 
 1   Processor  421 non-null    object 
 2   RAM_Type   409 non-null    object 
 3   RAM_Size   421 non-null    int64  
 4   Storage    421 non-null    int64  
 5   Disk_Type  421 non-null    object 
 6   OS_Type    421 non-null    object 
 7   MRP        421 non-null    float64
dtypes: float64(1), int64(2), object(5)
memory usage: 29.6+ KB


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder()
data[["Brand", "Processor","RAM_Type", "Disk_Type", "OS_Type"]] = enc.fit_transform(df_1[["Brand", "Processor","RAM_Type", "Disk_Type", "OS_Type"]])
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421 entries, 0 to 719
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Brand      421 non-null    float64
 1   Processor  421 non-null    float64
 2   RAM_Type   421 non-null    float64
 3   RAM_Size   421 non-null    int64  
 4   Storage    421 non-null    int64  
 5   Disk_Type  421 non-null    float64
 6   OS_Type    421 non-null    float64
 7   MRP        421 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 29.6 KB


**TRAIN_TEST SPLIT**

In [ ]:
df.iloc[:, :-1]

Product       MRP  \
0    Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...   36990.0   
1    Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...   39990.0   
2    ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...   32990.0   
3    HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...   49990.0   
4    ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...   49990.0   
..                                                 ...       ...   
713  DELL Core i5 12th Gen - (16 GB/512 GB SSD/Wind...   76590.0   
714  HP Pavilion Ryzen 7 Octa Core AMD R7-5800H - (...   90000.0   
715  ASUS Chromebook Flip Touch Celeron Dual Core -...   23490.0   
718  ASUS Zenbook Flip 14 OLED (2022) Touch Panel C...  125990.0   
719  Lenovo Ideapad Slim 3i Core i5 10th Gen - (8 G...   50990.0   

                                               Feature   Brand  RAM_Size  \
0    Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
1    Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...  Lenovo         8   
2    Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   
3    AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...      HP         8   
4    Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...    ASUS         8   
..                                                 ...     ...       ...   
713  Intel Core i5 Processor (12th Gen)16 GB DDR5 R...    DELL        16   
714  AMD Ryzen 7 Octa Core Processor16 GB DDR4 RAM6...      HP        16   
715  Intel Celeron Dual Core Processor4 GB LPDDR4 R...    ASUS         4   
718  Intel Core i7 Processor (12th Gen)16 GB LPDDR5...    ASUS        16   
719  Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...  Lenovo         8   

    RAM_Type  Storage Disk_Type  OS_Type  
0       DDR4      256       SSD  Windows  
1       DDR4      512       SSD  Windows  
2       DDR4      512       SSD  Windows  
3       DDR4      512       SSD  Windows  
4       DDR4      512       SSD  Windows  
..       ...      ...       ...      ...  
713     DDR5      512       SSD  Windows  
714     DDR4      512       SSD  Windows  
715   LPDDR4        1       SSD   Others  
718   LPDDR5      512       SSD  Windows  
719     DDR4      256       HDD  Windows  

[421 rows x 9 columns]

In [ ]:
X = data.iloc[:, :-1]
X

Brand  Processor  RAM_Type  RAM_Size  Storage  Disk_Type  OS_Type
0      7.0        1.0       0.0         8      256        1.0      2.0
1      7.0        1.0       0.0         8      512        1.0      2.0
2      2.0        1.0       0.0         8      512        1.0      2.0
3      5.0        0.0       0.0         8      512        1.0      2.0
4      2.0        1.0       0.0         8      512        1.0      2.0
..     ...        ...       ...       ...      ...        ...      ...
713    3.0        1.0       1.0        16      512        1.0      2.0
714    5.0        0.0       0.0        16      512        1.0      2.0
715    2.0        1.0       3.0         4        1        1.0      1.0
718    2.0        1.0       5.0        16      512        1.0      2.0
719    7.0        1.0       0.0         8      256        0.0      2.0

[421 rows x 7 columns]

In [ ]:
Y = data.iloc[:,-1]
Y

0       36990.0
1       39990.0
2       32990.0
3       49990.0
4       49990.0
         ...   
713     76590.0
714     90000.0
715     23490.0
718    125990.0
719     50990.0
Name: MRP, Length: 421, dtype: float64

In [ ]:
print('Independent feature shape : ', X.shape)
print('Dependent feature shape       : ', Y.shape)

Independent feature shape :  (421, 7)
Dependent feature shape       :  (421,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25)

In [ ]:
print('Training Data Shape   : ', x_train.shape)
print('Training Labels Shape : ', y_train.shape)
print('Testing Data Shape    : ', x_test.shape)
print('Testing Labels Shape  : ', y_test.shape)

Training Data Shape   :  (315, 7)
Training Labels Shape :  (315,)
Testing Data Shape    :  (106, 7)
Testing Labels Shape  :  (106,)


**DATA MODELLING**

In [ ]:
#Multiple Regression

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error

y_pred = regressor.predict(x_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6181656599226651
MAE 24239.31000280283


In [ ]:
#RANDOM FOREST

from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor(n_estimators = 10, max_depth = 12, random_state = 3)
rf_regressor.fit(x_train, y_train)

RandomForestRegressor(max_depth=12, n_estimators=10, random_state=3)

In [ ]:
y_pred = rf_regressor.predict(x_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.7166042713035025
MAE 17846.45201456453


In [ ]:
#K_Nearest

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors = 3)
knn_reg.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [ ]:
y_pred = knn_reg.predict(x_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.7585859234873477
MAE 16445.67610062893


In [ ]:
#Out of the Three Models - >Random Forest seems to give us a better accuracy.

In [ ]:
### Saving the Trained Model

import pickle
pickle_out = open("rf_regressor.pkl","wb")
pickle.dump(rf_regressor, pickle_out)
pickle_out.close()

In [ ]:
#Predicting the Price of the Laptop

rf_regressor.predict([[7.0, 1.0, 0.0, 8, 256,	1.0, 2.0]])

array([36007.65381873])

In [ ]:
df.Brand.unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [ ]:
data.Brand.unique()

array([ 7.,  2.,  5.,  3., 10., 15., 14.,  8.,  1.,  6., 11., 12., 13.,
        4.,  9.,  0.])

In [ ]:
data.Processor.unique()

array([1., 0., 2.])

In [ ]:
df.Processor.unique()

array(['Intel', 'AMD', 'Others'], dtype=object)

In [ ]:
data.RAM_Type.unique()

array([0., 1., 3., 6., 4., 5., 2.])

In [ ]:
df.RAM_Type.unique()

array(['DDR4', 'DDR5', 'LPDDR4', None, 'LPDDR4X', 'LPDDR5', 'LPDDR3'],
      dtype=object)

In [ ]:
data.Disk_Type.unique()

array([1., 0.])

In [ ]:
df.Disk_Type.unique()

array(['SSD', 'HDD'], dtype=object)

In [ ]:
data.OS_Type.unique()

array([2., 0., 1.])

In [ ]:
df.OS_Type.unique()

array(['Windows', 'Mac OS', 'Others'], dtype=object)